
  create table "public"."store" (
    "id" bigint generated by default as identity not null,
    "name" text
      );


alter table "public"."store" enable row level security;

CREATE UNIQUE INDEX store_pkey ON public.store USING btree (id);

alter table "public"."store" add constraint "store_pkey" PRIMARY KEY using index "store_pkey";

grant delete on table "public"."store" to "anon";

grant insert on table "public"."store" to "anon";

grant references on table "public"."store" to "anon";

grant select on table "public"."store" to "anon";

grant trigger on table "public"."store" to "anon";

grant truncate on table "public"."store" to "anon";

grant update on table "public"."store" to "anon";

grant delete on table "public"."store" to "authenticated";

grant insert on table "public"."store" to "authenticated";

grant references on table "public"."store" to "authenticated";

grant select on table "public"."store" to "authenticated";

grant trigger on table "public"."store" to "authenticated";

grant truncate on table "public"."store" to "authenticated";

grant update on table "public"."store" to "authenticated";

grant delete on table "public"."store" to "service_role";

grant insert on table "public"."store" to "service_role";

grant references on table "public"."store" to "service_role";

grant select on table "public"."store" to "service_role";

grant trigger on table "public"."store" to "service_role";

grant truncate on table "public"."store" to "service_role";

grant update on table "public"."store" to "service_role";


