INSERT INTO public.product
    (category_id, name, price, store_id, image_url, quantity_value, quantity_unit, price_per_unit, global_product_id)
VALUES
    (9, 'Suhkur Rimi Smart 1kg', 0.59, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_812369_PCE_EE', 1.0, 'kg', 0.59, NULL),
    (9, 'Meresool Rimi peenike 500g', 1.35, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_806991_PCE_EE', 0.5, 'kg', 2.7, NULL),
    (9, 'Jahvatatud paprika Santa Maria 22g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100273_PCE_EE', 0.022, 'kg', 40.909090909090914, NULL),
    (9, 'Pruun suhkur Rimi 500g', 1.49, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_813208_PCE_EE', 0.5, 'kg', 2.98, NULL),
    (9, 'Presspärm Nordic 50g', 0.4, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_267403_PCE_EE', 0.05, 'kg', 8.0, NULL),
    (9, 'Mandlilaastud Rimi 100g', 2.79, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_805827_PCE_EE', 0.1, 'kg', 27.9, NULL),
    (9, 'Himaalaja roosa sool Rimi peenike 500g', 1.49, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_807145_PCE_EE', 0.5, 'kg', 2.98, NULL),
    (9, 'Suhkur Dan Sukker 1kg', 1.09, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_165367_PCE_EE', 1.0, 'kg', 1.09, NULL),
    (9, 'Pruun suhkur Rimi 1kg', 2.98, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_813219_PCE_EE', 1.0, 'kg', 2.98, NULL),
    (9, 'Riivsai Tartu Mill 400g', 1.35, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_102732_PCE_EE', 0.4, 'kg', 3.375, NULL),
    (9, 'Riivsai Rimi 400g', 1.39, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_807909_PCE_EE', 0.4, 'kg', 3.4749999999999996, NULL),
    (9, 'Küpsetuspulber I Love Eco 120g', 2.09, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_813552_PCE_EE', 0.12, 'kg', 17.416666666666668, NULL),
    (9, 'Meresool Rimi jäme 500g', 1.35, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_806992_PCE_EE', 0.5, 'kg', 2.7, NULL),
    (9, 'Kookoshelbed Rimi 150g', 2.05, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_805845_PCE_EE', 0.15, 'kg', 13.666666666666666, NULL),
    (9, 'Hakklihamaitseaine Santa Maria 30g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100365_PCE_EE', 0.03, 'kg', 30.000000000000004, NULL),
    (9, 'Jahvatatud must pipar Rimi Smart 15g', 0.35, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_812160_PCE_EE', 0.015, 'kg', 23.333333333333332, NULL),
    (9, 'Kivisool jämedateraline Rimi Smart 1kg', 0.48, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_811466_PCE_EE', 1.0, 'kg', 0.48, NULL),
    (9, 'Vanillisuhkur I Love Eco 100g', 4.09, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_813551_PCE_EE', 0.1, 'kg', 40.9, NULL),
    (9, 'Söögisooda Lombardi 500g', 1.45, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_1008884_PCE_EE', 0.5, 'kg', 2.9, NULL),
    (9, 'Nelk Santa Maria 10g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_117137_PCE_EE', 0.01, 'kg', 90.0, NULL),
    (9, 'Broilerimaitseaine Santa Maria 30g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100328_PCE_EE', 0.03, 'kg', 30.000000000000004, NULL),
    (9, 'Must terapipar Santa Maria 22g', 1.29, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100528_PCE_EE', 0.022, 'kg', 58.63636363636364, NULL),
    (9, 'Kuivpärm Rimi Smart 12g', 0.25, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_814058_PCE_EE', 0.012, 'kg', 20.833333333333332, NULL),
    (9, 'Pitsamaitseaine Santa Maria 5g', 0.92, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100353_PCE_EE', 0.005, 'kg', 184.0, NULL),
    (9, 'Jahvatatud ingver Santa Maria 20g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100590_PCE_EE', 0.02, 'kg', 45.0, NULL),
    (9, 'Vürtsköömen Santa Maria 20g', 1.09, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_192848_PCE_EE', 0.02, 'kg', 54.5, NULL),
    (9, 'Himaalaja roosa sool Rimi jäme 500g', 1.49, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_806998_PCE_EE', 0.5, 'kg', 2.98, NULL),
    (9, 'Vahemere ürdisegu Santa Maria 12g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_121172_PCE_EE', 0.012, 'kg', 75.0, NULL),
    (9, 'Tuhksuhkur Dansukker 500g', 1.55, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_109409_PCE_EE', 0.5, 'kg', 3.1, NULL),
    (9, 'Kaneel jahvatatud Rimi 22g', 0.79, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_814501_PCE_EE', 0.022, 'kg', 35.909090909090914, NULL),
    (9, 'Karri Santa Maria 25g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100338_PCE_EE', 0.025, 'kg', 36.0, NULL),
    (9, 'Must pipar, purustatud Santa Maria 18g', 1.35, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_122325_PCE_EE', 0.018, 'kg', 75.00000000000001, NULL),
    (9, 'Kartulimaitseaine Santa Maria 350g', 4.85, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_134097_PCE_EE', 0.35, 'kg', 13.857142857142858, NULL),
    (9, 'Liha üldmaitseaine Santa Maria 35g', 0.99, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100318_PCE_EE', 0.035, 'kg', 28.28571428571428, NULL),
    (9, 'Koriander, purustatud Santa Maria 20g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_161026_PCE_EE', 0.02, 'kg', 45.0, NULL),
    (9, 'Küüslaugusool Santa Maria 40g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100352_PCE_EE', 0.04, 'kg', 22.5, NULL),
    (9, 'Muskaatpähkel Santa Maria 10g', 1.59, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_117138_PCE_EE', 0.01, 'kg', 159.0, NULL),
    (9, 'Küpsetusšokolaad tume ICA 200g', 4.99, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_803763_PCE_EE', 0.2, 'kg', 24.95, NULL),
    (9, 'Till Santa Maria 7g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100272_PCE_EE', 0.007, 'kg', 128.57142857142858, NULL),
    (9, 'Kaneelipulgad Kotanyi 12g', 1.59, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_132790_PCE_EE', 0.012, 'kg', 132.5, NULL)
ON CONFLICT (name, store_id) DO UPDATE
SET
    category_id = EXCLUDED.category_id,
    price = EXCLUDED.price,
    image_url = EXCLUDED.image_url,
    quantity_value = EXCLUDED.quantity_value,
    quantity_unit = EXCLUDED.quantity_unit,
    price_per_unit = EXCLUDED.price_per_unit,
    global_product_id = EXCLUDED.global_product_id;
