revoke delete on table "public"."user" from "anon";

revoke insert on table "public"."user" from "anon";

revoke references on table "public"."user" from "anon";

revoke select on table "public"."user" from "anon";

revoke trigger on table "public"."user" from "anon";

revoke truncate on table "public"."user" from "anon";

revoke update on table "public"."user" from "anon";

revoke delete on table "public"."user" from "authenticated";

revoke insert on table "public"."user" from "authenticated";

revoke references on table "public"."user" from "authenticated";

revoke select on table "public"."user" from "authenticated";

revoke trigger on table "public"."user" from "authenticated";

revoke truncate on table "public"."user" from "authenticated";

revoke update on table "public"."user" from "authenticated";

revoke delete on table "public"."user" from "service_role";

revoke insert on table "public"."user" from "service_role";

revoke references on table "public"."user" from "service_role";

revoke select on table "public"."user" from "service_role";

revoke trigger on table "public"."user" from "service_role";

revoke truncate on table "public"."user" from "service_role";

revoke update on table "public"."user" from "service_role";

alter table "public"."category" drop constraint "category_name_key";

alter table "public"."user" drop constraint "user_email_key";

alter table "public"."user" drop constraint "user_pkey";

drop index if exists "public"."category_name_key";

drop index if exists "public"."user_email_key";

drop index if exists "public"."user_pkey";

drop table "public"."user";

alter table "public"."category" alter column "id" drop default;

alter table "public"."category" alter column "id" add generated by default as identity;

alter table "public"."category" alter column "id" set data type bigint using "id"::bigint;

alter table "public"."category" alter column "name" drop not null;

alter table "public"."category" alter column "name" set data type character varying using "name"::character varying;

alter table "public"."category" enable row level security;

alter table "public"."product" add column "category_id" bigint;

alter table "public"."product" add column "store_id" bigint;

drop sequence if exists "public"."user_user_id_seq";

alter table "public"."product" add constraint "product_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.category(id) not valid;

alter table "public"."product" validate constraint "product_category_id_fkey";

alter table "public"."product" add constraint "product_store_id_fkey" FOREIGN KEY (store_id) REFERENCES public.store(id) not valid;

alter table "public"."product" validate constraint "product_store_id_fkey";


