create table "public"."global_product" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "brand" text,
    "category_id" bigint,
    "gtin" text,
    "notes" text
      );


alter table "public"."global_product" enable row level security;

CREATE UNIQUE INDEX global_product_pkey ON public.global_product USING btree
(id);

alter table "public"."global_product" add constraint "global_product_pkey" PRIMARY KEY
using index "global_product_pkey";

-- Link to category table
alter table "public"."global_product" add constraint "global_product_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES public.category(id)
not valid;

alter table "public"."global_product" validate constraint "global_product_category_id_fkey";

grant delete on table "public"."global_product" to "anon";

grant insert on table "public"."global_product" to "anon";

grant references on table "public"."global_product" to "anon";

grant select on table "public"."global_product" to "anon";

grant trigger on table "public"."global_product" to "anon";

grant truncate on table "public"."global_product" to "anon";

grant update on table "public"."global_product" to "anon";

grant delete on table "public"."global_product" to "authenticated";

grant insert on table "public"."global_product" to "authenticated";

grant references on table "public"."global_product" to "authenticated";

grant select on table "public"."global_product" to "authenticated";

grant trigger on table "public"."global_product" to "authenticated";

grant truncate on table "public"."global_product" to "authenticated";

grant update on table "public"."global_product" to "authenticated";

grant delete on table "public"."global_product" to "service_role";

grant insert on table "public"."global_product" to "service_role";

grant references on table "public"."global_product" to "service_role";

grant select on table "public"."global_product" to "service_role";

grant trigger on table "public"."global_product" to "service_role";

grant truncate on table "public"."global_product" to "service_role";

grant update on table "public"."global_product" to "service_role";
