INSERT INTO public.product
    (category_id, name, price, store_id, image_url)
VALUES
    (9, 'Suhkur Rimi Smart 1kg', 0.59, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_812369_PCE_EE'),
    (9, 'Meresool Rimi peenike 500g', 1.35, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_806991_PCE_EE'),
    (9, 'Jahvatatud paprika Santa Maria 22g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100273_PCE_EE'),
    (9, 'Mandlilaastud Rimi 100g', 2.79, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_805827_PCE_EE'),
    (9, 'Presspärm Nordic 50g', 0.4, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_267403_PCE_EE'),
    (9, 'Pruun suhkur Rimi 500g', 1.49, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_813208_PCE_EE'),
    (9, 'Riivsai Tartu Mill 400g', 1.29, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_102732_PCE_EE'),
    (9, 'Pruun suhkur Rimi 1kg', 2.98, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_813219_PCE_EE'),
    (9, 'Himaalaja roosa sool Rimi peenike 500g', 1.49, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_807145_PCE_EE'),
    (9, 'Suhkur Dan Sukker 1kg', 1.09, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_165367_PCE_EE'),
    (9, 'Riivsai Rimi 400g', 1.39, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_807909_PCE_EE'),
    (9, 'Meresool Rimi jäme 500g', 1.35, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_806992_PCE_EE'),
    (9, 'Küpsetuspulber I Love Eco 120g', 2.09, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_813552_PCE_EE'),
    (9, 'Kookoshelbed Rimi 150g', 2.05, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_805845_PCE_EE'),
    (9, 'Jahvatatud must pipar Rimi Smart 15g', 0.35, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_812160_PCE_EE'),
    (9, 'Vanillisuhkur I Love Eco 100g', 4.09, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_813551_PCE_EE'),
    (9, 'Kivisool jämedateraline Rimi Smart 1kg', 0.48, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_811466_PCE_EE'),
    (9, 'Söögisooda Lombardi 500g', 1.45, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_1008884_PCE_EE'),
    (9, 'Kuivpärm Rimi Smart 12g', 0.25, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_814058_PCE_EE'),
    (9, 'Kaneel jahvatatud Rimi 22g', 0.79, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_814501_PCE_EE'),
    (9, 'Nelk Santa Maria 10g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_117137_PCE_EE'),
    (9, 'Hakklihamaitseaine Santa Maria 30g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100365_PCE_EE'),
    (9, 'Himaalaja roosa sool Rimi jäme 500g', 1.49, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_806998_PCE_EE'),
    (9, 'Tuhksuhkur Dansukker 500g', 1.55, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_109409_PCE_EE'),
    (9, 'Suitsutatud magus paprika Rimi 25g', 0.95, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_814489_PCE_EE'),
    (9, 'Vahemere ürdisegu Santa Maria 12g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_121172_PCE_EE'),
    (9, 'Jahvatatud ingver Santa Maria 20g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100590_PCE_EE'),
    (9, 'Kartulimaitseaine Santa Maria 350g', 4.85, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_134097_PCE_EE'),
    (9, 'Vürtsköömen Santa Maria 20g', 1.09, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_192848_PCE_EE'),
    (9, 'Küpsetusšokolaad tume ICA 200g', 4.99, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_803763_PCE_EE'),
    (9, 'Must terapipar Santa Maria 22g', 1.29, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100528_PCE_EE'),
    (9, 'Broilerimaitseaine Santa Maria 30g', 0.9, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100328_PCE_EE'),
    (9, 'Kaneelipulgad Kotanyi 12g', 1.59, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_132790_PCE_EE'),
    (9, 'Vanilliinsuhkur Rimi Smart 35g', 0.39, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_812161_PCE_EE'),
    (9, 'Pitsamaitseaine Santa Maria 5g', 0.92, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100353_PCE_EE'),
    (9, 'Till Rimi 7g', 0.74, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_814494_PCE_EE'),
    (9, 'Tumeda šokolaadi nööbid Rimi 100g', 3.99, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_811018_PCE_EE'),
    (9, 'Küpsetuspulber Santa Maria 45g', 0.89, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_105050_PCE_EE'),
    (9, 'Jahvatatud kaneel Santa Maria 22g', 1.19, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_100376_PCE_EE'),
    (9, 'Loorberilehed Rimi 4g', 0.69, 2, 'https://rimibaltic-res.cloudinary.com/image/upload/b_white,c_limit,dpr_auto,f_auto,q_auto:low,w_auto/d_ecommerce:backend-fallback.png/MAT_814500_PCE_EE'),
ON CONFLICT (name, store_id) DO UPDATE
SET
    category_id = EXCLUDED.category_id,
    price = EXCLUDED.price,
    image_url = EXCLUDED.image_url;
